version: '3.7'

networks:
  test:
    name: test

services:
  api:
    container_name: test_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "yarn start:dev"
    env_file:
      - .env
    networks:
      - test
    depends_on:
      - postgres

  postgres:
    container_name: test_postgres
    image: postgres:12
    networks:
      - test
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
